#!/bin/bash -e

babel=./node_modules/.bin/babel
webpack=./node_modules/.bin/webpack
BUILD="$webpack --devtool source-map"

# Clean old build
rm -rf build/

# Generate bundle
mkdir -p dist/
eval $BUILD
eval "MINIFY=1 $BUILD"

# Transpile ES6
$babel index.js -d build/ --presets babel-preset-es2015

# Copy package
cp README.md build/
node -p 'p=require("./package");p.scripts=p.devDependencies=undefined;JSON.stringify(p,null,2)' > build/package.json
